//ProjectEuler-problem2.java
/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

public class problem2 {
	public static void main(String args[]) {
		int num1 = 1, num2 = 2, nextNum = 0, evenTotal = 0;
		String evenNumbers = "";
		
		while(nextNum <= 4000000) {
			nextNum = num1 + num2;
			if(num2%2==0) {
				evenTotal += num2;
				evenNumbers += num2 + ", ";
			}
			num1 = num2;
			num2 = nextNum; 
		}
		System.out.println("Find the sum of the even-valued terms in the Fibonacci sequence whose values do not exceed four million.\n");
		System.out.println("The total of even numbers is: " + evenTotal);
		System.out.println("The even numbers are: " + evenNumbers);
	}
}